first_number =input('Input Your First Number : ')
second_number =input('Input Your Second Number : ')
third_number =input('Input Your Third Number : ')
fourth_number =input('Input Your Fourth Number : ')
fifth_number =input('Input Your Fifth Number : ')
print('Float of %s Equal'%first_number,float(first_number))
print('Complex of %s Equal'%first_number,complex(first_number))
print('Float of %s Equal'%second_number,float(second_number))
print('Complex of %s Equal'%second_number,complex(second_number))
print('Float of %s Equal'%third_number,float(third_number))
print('Complex of %s Equal'%third_number,complex(third_number))
print('Float of %s Equal'%fourth_number,float(fourth_number))
print('Complex of %s Equal'%fourth_number,complex(fourth_number))
print('Float of %s Equal'%fifth_number,float(fifth_number))
print('Complex of %s Equal'%fifth_number,complex(fifth_number))